---
language: php

os: linux

# Activate build config validation.
# @see https://docs.travis-ci.com/user/build-config-validation
version: ~> 1.0

# The lowest version of PHP supported by all of Drupal, Acquia, and ORCA itself.
# @see https://www.drupal.org/docs/8/system-requirements/php-requirements
# @see https://docs.acquia.com/acquia-cloud/arch/tech-platform/
php: "7.2"

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.rvm"
    - "${TMPDIR:-/tmp}/phpstan/cache"

env:
  global:
    - ORCA_SUT_NAME=drupal/media_acquiadam
    - ORCA_SUT_BRANCH=8.x-1.x
    - ORCA_VERSION=^2
    - ORCA_TELEMETRY_ENABLE=TRUE

matrix:
  fast_finish: true
  include:
    - { name: "Static code analysis", env: ORCA_JOB=STATIC_CODE_ANALYSIS }
    - { name: "Deprecated code scan", env: ORCA_JOB=DEPRECATED_CODE_SCAN }
    - { name: "Isolated test w/ recommended package versions", env: ORCA_JOB=ISOLATED_RECOMMENDED }
    - { name: "Integrated test w/ recommended package versions", env: ORCA_JOB=INTEGRATED_RECOMMENDED }
    - { name: "Integrated test w/ recommended package versions & previous minor release of Drupal core", env: ORCA_JOB=CORE_PREVIOUS }
    - { name: "Isolated test w/ dev package versions", env: ORCA_JOB=ISOLATED_DEV }
    - { name: "Integrated test w/ dev package versions", env: ORCA_JOB=INTEGRATED_DEV }
    - { name: "Integrated test w/ dev package versions & next minor dev version of Drupal core", env: ORCA_JOB=CORE_NEXT }
    - { name: "D9 readiness test", php: "7.3", env: ORCA_JOB=D9_READINESS}
  allow_failures:
    - env: ORCA_JOB=ISOLATED_DEV
    - env: ORCA_JOB=INTEGRATED_DEV
    - env: ORCA_JOB=CORE_NEXT

before_install:
  - composer self-update --1
  - composer create-project --no-dev acquia/orca ../orca "$ORCA_VERSION"
  - ../orca/bin/travis/before_install.sh

install:
  - ../orca/bin/travis/install.sh
  - ./tests/travis/install.sh

before_script: ../orca/bin/travis/before_script.sh

script: ../orca/bin/travis/script.sh

before_cache: ../orca/bin/travis/before_cache.sh

after_success: ../orca/bin/travis/after_success.sh

after_failure: ../orca/bin/travis/after_failure.sh

after_script: ../orca/bin/travis/after_script.sh

notifications:
  slack:
    rooms:
      - secure: mmOkXrX1bhdb/7Zai3aVKadrxDatw8DXjvBXXJFDbv5fXYerie2hHibIpaUEtXKygrOMQUA5ZlNVkLYTnwe0iUsD90rrSYM/C7/8mZIOXMIXGARsJL5pspsb7nzPisuokEIEBMqk/Y1pkK66qpNWGesBx4vtZ76SOgUYK/ZkjdhUlLdQ/F4X8XrTod8JcEuqUoW9zLXeasdum7VGdY7/SRpUJBIHLpLw6HjfuumHfQlKZCUX29jtre/o70wY03cBKPFXFh6AJ3a0w/rOu1MwSjBTSKaAiNYGvrJlqJYZIguV+pSKplGWh6aQe+1JCZ35QqKC3ODOa5FyuMsJE0yBMRdXJlAi8czAMbf91x+/zRjmXY6MtABm3JEUMaTfoSCUDKPm1ThS07QRfCJ/oh01IZU272lSSlTneXGPcHH8koBF8/0JprJz3XcejPKqsYnZpW5x93YK8TNYlWnhDVfssyGQznhJ1UIlwVTQTFnuf31QzKoldCQmx2FX5iPyP9Pz7Bx/W8+vW1sTrLhNeP/uDv2iAhZ7a9f6Fz9zKcRVAZ7VdHFMVPxNyZ2+cNAeK/SYPscTd4v+qkzxUp/iQ98piIUCL8TPNFtEAUROdEiyh55WgQymEmkvPpy9budV4bUFQxIEMdMWqM/Fcl5s7ae7HJtHm0kHxBTz71umr2TLihg=
    on_success: change
    on_failure: change
    if: branch = env(ORCA_SUT_BRANCH)
