---
language: php

os: linux
dist: focal

version: ~> 1.0

php: "7.4"

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.rvm"
    - "${TMPDIR:-/tmp}/phpstan/cache"

services:
  - mysql

env:
  global:
    - ORCA_SUT_NAME=drupal/media_acquiadam
    - ORCA_SUT_BRANCH=2.x
    - ORCA_VERSION=^3
    - ORCA_TELEMETRY_ENABLE=TRUE

matrix:
  fast_finish: true
  include:
    - { env: ORCA_JOB=STATIC_CODE_ANALYSIS, name: "Static code analysis" }
    - { env: ORCA_JOB=LOOSE_DEPRECATED_CODE_SCAN, name: "Loose deprecated code scan" }
    - { env: ORCA_JOB=STRICT_DEPRECATED_CODE_SCAN, name: "Strict deprecated code scan" }
    - { env: ORCA_JOB=ISOLATED_TEST_ON_CURRENT, name: "Isolated test w/ recommended package versions" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_CURRENT, name: "Integrated test w/ recommended package versions" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_PREVIOUS_MINOR, name: "Integrated test w/ recommended package versions & previous minor release of Drupal core" }
    - { env: ORCA_JOB=ISOLATED_TEST_ON_CURRENT_DEV, name: "Isolated test w/ dev package versions" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_CURRENT_DEV, name: "Integrated test w/ dev package versions" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR, name: "Integrated test w/ package versions & next minor version of Drupal core" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR_DEV, name: "Integrated test w/ dev package versions & next minor dev version of Drupal core" }
  allow_failures:
    - env: ORCA_JOB=LOOSE_DEPRECATED_CODE_SCAN
    - env: ORCA_JOB=ISOLATED_TEST_ON_CURRENT_DEV
    - env: ORCA_JOB=INTEGRATED_TEST_ON_CURRENT_DEV
    - env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR
    - env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR_DEV


before_install:
  - composer create-project --no-dev acquia/orca ../orca "$ORCA_VERSION"
  - ../orca/bin/travis/before_install.sh

install:
  - ../orca/bin/travis/install.sh
  - ./tests/travis/install.sh

before_script: ../orca/bin/travis/before_script.sh

script:
  - ./tests/travis/script.sh
  - ../orca/bin/travis/script.sh

before_cache: ../orca/bin/travis/before_cache.sh

after_success: ../orca/bin/travis/after_success.sh

after_failure: ../orca/bin/travis/after_failure.sh

after_script: ../orca/bin/travis/after_script.sh

notifications:
  slack:
    rooms:
      - secure: mmOkXrX1bhdb/7Zai3aVKadrxDatw8DXjvBXXJFDbv5fXYerie2hHibIpaUEtXKygrOMQUA5ZlNVkLYTnwe0iUsD90rrSYM/C7/8mZIOXMIXGARsJL5pspsb7nzPisuokEIEBMqk/Y1pkK66qpNWGesBx4vtZ76SOgUYK/ZkjdhUlLdQ/F4X8XrTod8JcEuqUoW9zLXeasdum7VGdY7/SRpUJBIHLpLw6HjfuumHfQlKZCUX29jtre/o70wY03cBKPFXFh6AJ3a0w/rOu1MwSjBTSKaAiNYGvrJlqJYZIguV+pSKplGWh6aQe+1JCZ35QqKC3ODOa5FyuMsJE0yBMRdXJlAi8czAMbf91x+/zRjmXY6MtABm3JEUMaTfoSCUDKPm1ThS07QRfCJ/oh01IZU272lSSlTneXGPcHH8koBF8/0JprJz3XcejPKqsYnZpW5x93YK8TNYlWnhDVfssyGQznhJ1UIlwVTQTFnuf31QzKoldCQmx2FX5iPyP9Pz7Bx/W8+vW1sTrLhNeP/uDv2iAhZ7a9f6Fz9zKcRVAZ7VdHFMVPxNyZ2+cNAeK/SYPscTd4v+qkzxUp/iQ98piIUCL8TPNFtEAUROdEiyh55WgQymEmkvPpy9budV4bUFQxIEMdMWqM/Fcl5s7ae7HJtHm0kHxBTz71umr2TLihg=
    on_success: change
    on_failure: change
    if: branch = env(ORCA_SUT_BRANCH)
