# Schema for the configuration files of the acquiadam module.
acquiadam.settings:
  type: config_object
  label: 'Acquia DAM settings'
  mapping:
    domain:
      type: string
      label: 'Acquia DAM domain'
    token:
      type: string
      label: 'Acquia DAM authentication token'
    search_endpoint:
      type: string
      label: 'Search endpoint'
    client_registration:
      type: string
      label: 'Client registration'
    client_hash:
      type: string
      label: 'Client hash'
    sync_interval:
      type: integer
      label: 'Sync interval'
    sync_method:
      type: string
      label: 'Sync method'
    size_limit:
      type: integer
      label: 'Size limit'
    image_quality:
      type: integer
      label: 'Image quality'
    oauth:
      type: mapping
      label: 'Oauth'
      mapping:
        excluded_redirect_keys:
          type: sequence
          label: 'Excluded redirect keys'
          sequence:
            type: string
            label: 'Key'
    sync_perform_delete:
      type: integer
      label: 'Delete inactive drupal dam assets'
    num_assets_per_page:
      type: integer
      label: 'Number of assets per page'
    fallback_thumbnail:
      type: uri
      label: 'Fallback thumbnail'
    report_asset_usage:
      type: integer
      label: 'Report asset usage'

media.source.acquiadam_asset:
  type: media.source.field_aware
  label: 'Acquia DAM asset media source configuration'
