# Schema for the configuration files of the media_acquiadam module.
media_acquiadam.settings:
  type: config_object
  label: 'Media Acquia DAM settings'
  mapping:
    username:
      type: string
      label: 'Acquia DAM username'
    password:
      type: string
      label: 'Acquia DAM password'
    client_id:
      type: string
      label: 'Client ID for Acquia DAM API'
    secret:
      type: string
      label: 'Secret for Acquia DAM API'
    sync_interval:
      type: integer
      label: 'Sync interval'
    size_limit:
      type: integer
      label: 'Size limit'
    oauth:
      type: mapping
      label: 'Oauth'
      mapping:
        excluded_redirect_keys:
          type: sequence
          label: 'Excluded redirect keys'
          sequence:
            type: string
            label: 'Key'
    notifications_sync:
      type: integer
      label: 'Notifications sync'
    perform_sync_delete:
      type: integer
      label: 'Delete inactive drupal dam assets'
    num_images_per_page:
      type: integer
      label: 'Number of images per page'
    fallback_thumbnail:
      type: uri
      label: 'Fallback thumbnail'
    samesite_cookie_disable:
      type: integer
      label: 'Disable SameSite Cookie Bypass'

media.source.acquiadam_asset:
  type: media.source.field_aware
  label: 'Acquia DAM asset media source configuration'
