services:
  php:
    # Here's where you specify your custom Docker image and preferred tag.
    image: quay.io/q0rban/drupal:8.8
    default: true
    depends:
      - mysql
    commands:
      update: |
        set -eux
        # Check out a branch using the unique Tugboat ID for this repository, to ensure
        # we don't clobber an existing branch.
        git checkout -b $TUGBOAT_REPO_ID
        # Composer is hungry. You need a Tugboat project with a pretty sizeable chunk of
        # memory for this to work.
        export COMPOSER_MEMORY_LIMIT=-1
        # This is an environment variable we added in the Dockerfile that provides the
        # path to Drupal composer root (not the web root).
        cd $DRUPAL_COMPOSER_ROOT
        # We configure the Drupal project to use the checkout of the module as a
        # Composer package repository.
        composer config repositories.tugboat vcs $TUGBOAT_ROOT
        # Now we can require this module, specifing the branch name we created above
        # that uses the $TUGBOAT_REPO_ID environment variable.
        composer require drupal/media_acquiadam:dev-$TUGBOAT_REPO_ID
        # bring in require-dev dependency modules.
        composer require drupal/entity_browser:~2.0
        composer require drupal/linkit:~5.0
        # Install Drupal!
        vendor/bin/drush --yes --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat site:install standard
        # Enable our module!
        vendor/bin/drush --yes en media_acquiadam
        vendor/bin/drush --yes en media_acquiadam_example
        vendor/bin/drush --yes en entity_browser
        vendor/bin/drush --yes en linkit
        vendor/bin/drush --yes en watchdog
        # Setup secret sauce
        vendor/bin/drush --yes cset media_acquiadam.settings username $dam_username
        vendor/bin/drush --yes cset media_acquiadam.settings password $dam_password
        vendor/bin/drush --yes cset media_acquiadam.settings client_id $dam_client_id
        vendor/bin/drush --yes cset media_acquiadam.settings secret $dam_secret
      build: |
        set -eux
        export COMPOSER_MEMORY_LIMIT=-1
        cd $DRUPAL_COMPOSER_ROOT
        composer install --optimize-autoloader
        # Update this module, including all dependencies.
        composer update drupal/media_acquiadam --with-all-dependencies
        # Run Drupal update scripts.
        vendor/bin/drush --yes updb
        vendor/bin/drush cache:rebuild
  mysql:
    image: tugboatqa/percona:5.6
    commands:
      init:
        - printf '[mysqld]\ninnodb_log_file_size = 50331648\nmax_allowed_packet = 128M\n' > /etc/my.cnf.d/zzz.cnf
        - sv restart percona
