<?php

/**
 * @file
 * Provide views data for media_acquiadam_report.module.
 */

/**
 * Implements hook_views_query_alter().
 *
 * Adds query condition to DAM listing to filter media bundles.
 */
function media_acquiadam_report_views_query_alter($view, $query) {
  if ($view->id() == 'acquia_dam_reporting' && $view->getDisplay(
    )->display['id'] == 'asset_report') {
    // Limit the view to 'acquiadam_asset' media bundles.
    $acquiadam_bundles = media_acquiadam_get_bundle_asset_id_fields();
    $acquiadam_bundles = array_keys($acquiadam_bundles);
    // Add media bundle query condition.
    $query->addWhere(
      'conditions',
      'media_field_data.bundle',
      $acquiadam_bundles,
      'in'
    );
  }
}

/**
 * Implements hook_views_data_alter().
 *
 * Adds a DAM source id field for use in the DAM listing.
 */
function media_acquiadam_report_views_data_alter(array &$data) {
  $data['media']['acquiadam_source_id'] = [
    'title' => t('Acquia DAM source id'),
    'field' => [
      'title' => t('Acquia DAM source id'),
      'help' => t(
        'The source id from the field configured in the asset mapping.'
      ),
      'id' => 'acquiadam_source_id',
    ],
  ];
}
